FROM mysql:5.7

MAINTAINER svyatoslav <svyatoslav12381@gmail.com>

RUN apt-get update

ENV MYSQL_ROOT_PASSWORD password
ENV MYSQL_DATABASE kozak
ENV MYSQL_USER svyatoslav
ENV MYSQL_PASSWORD svyatoslav

EXPOSE 3306
