Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/bionic64"
  end

  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/7"
    config.vm.provision "shell" do |s|
      s.inline = " 
      touch Kozak
      apt-get update
      apt-get install -y apache2"
    centos.vm.network "forwarded_post", guest: 80, host: 8080
   end
end 
