version: "3.8"

services:

  apache:
    build:
      context: ./apache-server
      dockerfile: Dockerfile
    links:
      - mysql

  mysql:
    build:
      context: ./mysql-server
      dockerfile: Dockerfile
