version: "3.8"

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: svyatoslav
    ports:
      - 3308:3306

  apache:
    image: httpd:latest
    restart: always
    ports:
      - 80:8080
    links:
      - db
    
