Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
  ubuntu.vm.box = "ubuntu/bionic64"
  ubuntu.vm.network "forwarded_post", guest: 80, host: 8080
  ubuntu.vm.synced_folder "~/014/hometask_5/Kozak, "/home/vagrant/"
  ubuntu.vm.provision "shell" do |s|
    s.inline = "
    "apt update
    apt -y install docker-ce
    docker run -d
    pip install docker-compose 
    docker-compose up -d"
  end
end 
